title: mrtc0.log
subtitle: tail -f /var/log/mrtc0.log
description: null
author: mrtc0
language: en
timezone: Asia/Tokyo
url: 'https://blog.mrtc0.com/'
root: /
permalink: ':year/:month/:day/'
permalink_defaults:
  category: uncategorized
  id: none
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace: null
default_category: uncategorized
category_map: null
tag_map: null
date_format: YYYY-MM-DD
time_format: 'HH:mm:ss'
per_page: 10
pagination_dir: page
theme: landscape-plus
deploy:
  type: git
  repo: 'git@github.com:mrt-k/blog.mrtc0.com.git'
  branch: gh-pages
  message: "Updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
disqus_shortname: mrtc0
